spring.application.name=fiscalizei


# ??? Pasta de uploads ?????????????????????????????????????
# Caminho relativo à raiz do projeto onde as fotos serão salvas
upload.dir=uploads/usuarios

# ??? Tamanho máximo de upload ?????????????????????????????
# Aumenta o limite padrão do Spring (1MB) para suportar fotos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB